version: "3.6"

services:
  app:
    build: .
    container_name: SNResistance
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10.5-alpine
    container_name: SNResistancePostgres
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USERNAME
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.11-alpine
    container_name: SNResistanceRedis
    restart: always
    ports:
      - "$REDIS_PORT:6379"

networks:
  default:
    name: SNResistance

volumes:
  psql-data:
    name: SNResistancePSQL
