version: "3"

services:
  app:
    build: .
    container_name: SNResistance
    restart: unless-stoppeds
    environment:
      # You should change SNRESISTANCE_TOKEN in .env file (you can also set
      # environment variable yourself using command `export SNRESISTANCE_TOKEN=CHANGE IT TO TOKEN`)
      - SNRESISTANCE_TOKEN=${SNRESISTANCE_TOKEN}
      - SNRESISTANCE_DEVMODE=${SNResistance_DEVMODE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11.1-alpine
    container_name: SNResistancePostgreSQL
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3-alpine
    container_name: SNResistanceRedis
    restart: unless-stopped
    ports:
      - "6379:6379"

networks:
  default:
    name: SNResistance

volumes:
  postgresql-data:
    name: postgresql-data
