version: "3.6"

services:
  app:
    build: .

  redis:
    image: redis:4.0.10-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
